name: Daily NFT Refresh

on:
  schedule:
  workflow_dispatch:
    - cron: '5 0 * * *'  # Runs every day at 00:05 UTC

jobs:
  refresh-part1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Run refresh for tokens 1-2400
      env:
        OPENSEA_API_KEY: ${{ secrets.OPENSEA_API_KEY }}
      run: python script.py 1 2400

  refresh-part2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Run refresh for tokens 2401-4800
      env:
        OPENSEA_API_KEY: ${{ secrets.OPENSEA_API_KEY }}
      run: python script.py 2401 4800
